server:
  port: 8080
spring:
  jms:
    template:
      default-destination: test.queue
  datasource:
    driverClassName: org.h2.Driver
    password: password
    username: sa
    url: jdbc:h2:mem:testdb
  activemq:
    packages:
      trust-all: 'true'
  profiles:
    active: dev
  jpa:
    open-in-view: false # Open Session in View (OSIV)
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: false
        ejb:
          interceptor: com.example.demo.config.MyInterceptor
#  config:
#    activate:
#      on-profile: dev

management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: 'true'
    java:
      enabled: 'true'
  endpoint:
    health:
      show-details: always
info:
  app:
    encoding: '@project.build.sourceEncoding@'
    java:
      source: '@java.version@'
      target: '@java.version@'
  contact:
    email: email@email.com

logging:
  level:
    root: WARN
    com.example.demo: DEBUG

hibernate:
  generate_statistics: true
  max_fetch_depth: 3 # for inner eager join
  connection:
    isolation: 1


---
spring:
  profiles: docker